# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-03-08 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=32)),
                ('subscription_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('vnf_pkg_id', models.CharField(max_length=100)),
                ('vnfd_id', models.CharField(max_length=100)),
                ('change_type', models.CharField(max_length=15)),
                ('operational_state', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'vnfpkgm_notification',
            },
        ),
        migrations.CreateModel(
            name='OnapVnfPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csar_id', models.CharField(max_length=36)),
                ('vnfd_id', models.CharField(max_length=36)),
                ('vnf_pkg_id', models.CharField(max_length=36)),
                ('vnfd_provider', models.CharField(max_length=100)),
                ('vnfd_version', models.CharField(max_length=30)),
                ('vnf_version', models.CharField(max_length=30)),
                ('download_url', models.TextField(max_length=20000)),
            ],
            options={
                'db_table': 'vnfpkgm_onap_vnf_package',
            },
        ),
        migrations.CreateModel(
            name='PkgmSubscriptionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.TextField(blank=True, max_length=20000)),
                ('callback_url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'vnfpkgm_pkgm_subscription_request',
            },
        ),
    ]
